# SPDX-FileCopyrightText: 2024 Infineon Technologies AG
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "docs/api-reference/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Infineon Technologies AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/images/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Infineon Technologies AG"
SPDX-License-Identifier = "MIT"
